### ISSUE TITLE
class_file?

### ISSUE THREAD

**Issue by baolinliu** [Deep-Magic/COCO-Style-Dataset-Generator-GUI#3]
So I tried to run your segments.py file and it asked for a class_file, not sure what it is.  I'm not sure if there are some missing steps in your documentation.  

Thanks.

**Comment by hanskrupakar** [comment]
Hey I need to update the README. `class_file` refers to a file with the list of classes to appear along with the image, line by line.

**Comment by baolinliu** [comment]
I would love to use your work, when do you think you will update the readme to reflect the changes?
