### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gynr** [Deep-Magic/COCO-Style-Dataset-Generator-GUI#5]
python3 segment.py -i images/ -c classes/products.txt
Traceback (most recent call last):
  File "segment.py", line 434, in <module>
    gen = COCO_dataset_generator(fig, ax, args)
  File "segment.py", line 86, in __init__
    if os.path.exists(self.img_paths[self.index][:-3]+'txt'):
IndexError: list index out of range

**Comment by hanskrupakar** [comment]
Fixed. Try now!
You just need to make sure the images directory you give isn't empty.

**Comment by gynr** [comment]
Thanks.

**Comment by hwjung92** [comment]
thank your for providing this program.
but, it is hard to use. I failed to create COCO file.
please, upgrade it more.

**Comment by hanskrupakar** [comment]
You need to use [create_json_file.py](https://github.com/Deep-Magic/COCO-Style-Dataset-Generator-GUI/blob/master/create_json_file.py) to create the COCO dataset file. It's pretty self-contained. Use `python create_json_file.py -h` for help.
