### ISSUE TITLE
model

### ISSUE THREAD

**Issue by joydeepmedhi** [Deep-Magic/COCO-Style-Dataset-Generator-GUI#7]
**import model as modellib**
what is this model?

Traceback (most recent call last):
  File "segment_bbox_only.py", line 306, in <module>
    gen = COCO_dataset_generator(fig, ax, args['image_file'], args['classes_file'], args['weights_path'], args['json_file'])
  File "segment_bbox_only.py", line 112, in __init__
    import model as modellib
ImportError: No module named 'model'

**Comment by hanskrupakar** [comment]
Please run with the `--no_feedback flag` to disable pre-trained model overlays if you're not using that.
