### ISSUE TITLE
issue of  " /usr/local/lib/python3.5/dist-packages/matplotlib/figure.py:448: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.   % get_backend())  "

### ISSUE THREAD

**Issue by nooriahmed** [Deep-Magic/COCO-Style-Dataset-Generator-GUI#8]
Really great work,But  i am looking for some help, could you please provide some solutions on this uissue /usr/local/lib/python3.5/dist-packages/matplotlib/figure.py:448: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  % get_backend())

**Comment by hanskrupakar** [comment]
You're running on a non-GUI based environment. You can explicitly set matplotlib backend using 
```
import matplotlib
matplotlib.use('TkAgg') # TkAgg, WX, QTAgg, QT4Agg are possible backends
```
For more information, check out [this SO answer](https://stackoverflow.com/questions/4930524/how-can-i-set-the-backend-in-matplotlib-in-python)
