### ISSUE TITLE
BagsConfig() 

### ISSUE THREAD

**Issue by BogdanS94** [Deep-Magic/COCO-Style-Dataset-Generator-GUI#9]
Could you help me with an little issue? 
I'm trying to run this code but I really don't understand where is demo.py file. 
I received error at from demo import BagsConfig 
![image](https://user-images.githubusercontent.com/45510875/50514658-4a5e7a80-0aa8-11e9-88a1-f4bafa595f3d.png)

**Comment by hanskrupakar** [comment]
Is the maskrcnn_dir argument set correctly to point to your local Mask RCNN directory? BagsConfig is imported just above line 103.

**Comment by BogdanS94** [comment]
Hello, 
Yeah I think that patch to Mask RCNN directory it's ok. But i can't find any demo files.. I sow in segment.py that BagsConfig it's imported from demo module. 
Probably this file is missing from Mask RCNN folder. 

Do you know where this file should be? 
Thanks

**Comment by hanskrupakar** [comment]
https://github.com/hanskrupakar/Mask_RCNN/blob/master/demo.py
